ci:
  - any:
      - changed-files:
          - any-glob-to-any-file: ['.github/workflows/**']

documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file: ['doc/source/**/*.rst', 'README.rst']

maintenance:
  - any:
      - changed-files:
          - any-glob-to-any-file: ['.github/**/*', 'pyproject.toml']

examples:
  - any:
      - changed-files:
          - any-glob-to-any-file: ['examples/**/*']

testing:
  - any:
      - changed-files:
          - any-glob-to-any-file: ['tests/**']
